# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets

from database.Database import db
from interface.AuthMain import Ui_MainWindow


class AuthWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()  # QMainWindow.__init__()
        self.ui = Ui_MainWindow()  # Интерфейс
        self.ui.setupUi(self)  # Загрузка интерфейса в наш класс с логикой
        self.ui.AutoButton.clicked.connect(self.handle_click)

    def handle_click(self):
        username = self.ui.lineEdit.text()
        password = self.ui.lineEdit_2.text()

        if db.authorize_user(username, password):
            QtWidgets.QMessageBox.information(self, "Успех", "Авторизованы")
            from .Partners import Partners

            self.partners = Partners()
            self.partners.show()

        else:
            QtWidgets.QMessageBox.warning(self, "Error", "Ошибка")
