# Form implementation generated from reading ui file '.\ui\EditPartner.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from .PartnerCard import PartnerCardInfo
from database.Database import db
from interface.editPartner import Ui_MainWindow


class EditPartner(QtWidgets.QMainWindow):
    def __init__(self, partner_info: PartnerCardInfo):
        super().__init__()
        self.partner_info = partner_info
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.load_info()
        self.load_partner_types()

    def load_info(self):
        self.ui.partner_name_edit.setText(self.partner_info.partner_name)
        self.ui.first_name_edit.setText(self.partner_info.first_name)
        self.ui.last_name_edit.setText(self.partner_info.last_name)
        self.ui.middle_name_edit.setText(self.partner_info.middle_name)

        self.ui.email_edit.setText(self.partner_info.email)
        self.ui.phone_edit.setText(self.partner_info.phone_partner)
        self.ui.address_edit.setText(self.partner_info.address)
        self.ui.INN_edit.setText(self.partner_info.inn_number)
        self.ui.rating_spinbox.setValue(self.partner_info.rating)

    def load_partner_types(self):
        types = db.get_partners_types()
        for t in types:
            self.ui.typeBox.addItem(t["name"], t["id"])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
