# Form implementation generated from reading ui file '.\master_pol\ui\partners.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from database.Database import db
from dto.partner_card_info import PartnerCardInfo
from interface.Partners import Ui_Partners
from .PartnerCard import PartnerCard


class Partners(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Partners()
        self.ui.setupUi(self)
        self.ui.AutoButton.clicked.connect(self.on_clicked_add)
        self.load_partners()

    def load_partners(self):
        self.clear_layout()
        partners = db.show_partners()  # много строчек
        for partner in partners:
            discount = db.get_disc(int(partner["id"]))
            with db.connection.cursor() as cur:
                cur.execute(
                    "SELECT email_partner, address, INN FROM partners WHERE id = %s",
                    (partner["id"],),
                )
                result = cur.fetchone()
                partner.update(result)

            partner_info = PartnerCardInfo(
                partner["id"],
                partner["type_name"],
                partner["partner_name"],
                partner["first_name_director"],
                partner["last_name_director"],
                partner["middle_name_director"],
                partner["email_partner"],
                partner["phone_partner"],
                partner["address"],
                partner["INN"],
                partner["rating"],
                discount,
            )
            partnerCard = PartnerCard(partner_info)
            partnerCard.double_clicked.connect(self.load_choices)
            self.ui.verticalLayout_2.addWidget(partnerCard)

    def clear_layout(self):
        while self.ui.verticalLayout_2.count():
            item = self.ui.verticalLayout_2.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.setParent(None)
                widget.deleteLater()

    # TODO: обработать двойной клик по карточке
    def load_choices(self, partner_info: PartnerCardInfo):
        from .AdminChoice import Admin
        self.Admin = Admin(partner_info)
        self.Admin.deleted.connect(self.load_partners)
        self.Admin.show()

    def on_clicked_add(self, partner_info):
        from .AddPartner import AddPartner

        self.AddPartner = AddPartner(partner_info)
        self.AddPartner.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Partners = QtWidgets.QMainWindow()
    ui = Ui_Partners()
    ui.setupUi(Partners)
    Partners.show()
    sys.exit(app.exec())
