# Form implementation generated from reading ui file 'partner_card.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from dto.partner_card_info import PartnerCardInfo
from interface.PartnerCard import Ui_Frame


class PartnerCard(QtWidgets.QFrame):
    double_clicked = QtCore.pyqtSignal(PartnerCardInfo)

    def __init__(self, partner_info: PartnerCardInfo):
        super().__init__()
        self.ui = Ui_Frame()
        self.partner_info = partner_info
        self.ui.setupUi(self)
        self.setData()

        self.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)

    def mouseDoubleClickEvent(self, event):
        self.double_clicked.emit(self.partner_info)
        event.accept()

    def setData(self):
        fio = f"{self.partner_info.last_name} {self.partner_info.first_name} {self.partner_info.middle_name or ''}"
        self.ui.name.setText(fio)
        self.ui.percentage.setText(f"{str(self.partner_info.discount)}%")
        self.ui.contacts.setText(self.partner_info.phone_partner)
        self.ui.comany.setText(
            f"{self.partner_info.type_name} | {self.partner_info.partner_name}"
        )
        self.ui.label.setText(f"Рейтинг: {str(self.partner_info.rating)}")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
