# Form implementation generated from reading ui file 'partners.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Partners(object):
    def setupUi(self, Partners):
        Partners.setObjectName("Partners")
        Partners.resize(451, 283)
        Partners.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.centralwidget = QtWidgets.QWidget(parent=Partners)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 435, 231))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.partners = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents_2)
        self.partners.setGeometry(QtCore.QRect(0, 0, 437, 175))
        self.partners.setObjectName("partners")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Partners.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Partners)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 18))
        self.menubar.setObjectName("menubar")
        Partners.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Partners)
        self.statusbar.setObjectName("statusbar")
        Partners.setStatusBar(self.statusbar)

        self.retranslateUi(Partners)
        QtCore.QMetaObject.connectSlotsByName(Partners)

    def retranslateUi(self, Partners):
        _translate = QtCore.QCoreApplication.translate
        Partners.setWindowTitle(_translate("Partners", "MainWindow"))
        self.partners.setHtml(_translate("Partners", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#79c564;\">Партнеры</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Partners = QtWidgets.QMainWindow()
    ui = Ui_Partners()
    ui.setupUi(Partners)
    Partners.show()
    sys.exit(app.exec())
