# Form implementation generated from reading ui file '.\ui\partners.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from database.Database import db
from ui_py.PartnerCard import PartnerCard, PartnerCardInfo


class Ui_Partners(object):
    def setupUi(self, Partners):
        Partners.setObjectName("Partners")
        Partners.resize(519, 555)
        Partners.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.centralwidget = QtWidgets.QWidget(parent=Partners)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet(
            "color: rgb(85, 255, 0);\n"
            'font: 75 14pt "MS Shell Dlg 2";\n'
            "font-weight: bold;"
        )
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 497, 463))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.main_layout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.main_layout)
        Partners.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Partners)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.menubar.setObjectName("menubar")
        Partners.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Partners)
        self.statusbar.setObjectName("statusbar")
        Partners.setStatusBar(self.statusbar)

        self.retranslateUi(Partners)
        QtCore.QMetaObject.connectSlotsByName(Partners)

    def retranslateUi(self, Partners):
        _translate = QtCore.QCoreApplication.translate
        Partners.setWindowTitle(_translate("Partners", "MainWindow"))
        self.label.setText(_translate("Partners", "Партнёры"))


class Partners(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Partners()
        self.ui.setupUi(self)
        self.load_partners()

    def load_partners(self):
        partners = db.show_partners()  # много строчек
        for partner in partners:
            discount = db.get_disc(int(partner["id"]))
            partner_info = PartnerCardInfo(
                partner["id"],
                partner["type_name"],
                partner["partner_name"],
                partner["first_name_director"],
                partner["last_name_director"],
                partner["middle_name_director"],
                partner["phone_partner"],
                partner["rating"],
                discount,
            )
            partnerCard = PartnerCard(partner_info)
            partnerCard.double_clicked.connect(self.load_edit_partner)
            self.ui.verticalLayout_2.addWidget(partnerCard)

    #TODO: обработать двойной клик по карточке
    def load_edit_partner(self, partner_info: PartnerCardInfo):
        from ui_py.editPartner import EditPartner

        self.editPartner = EditPartner(partner_info)
        self.editPartner.show()
