# Form implementation generated from reading ui file '.\master_pol\ui\partners.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from database.Database import db
from ui_py.PartnerCard import PartnerCard, PartnerCardInfo


class Ui_Partners(object):
    def setupUi(self, Partners):
        Partners.setObjectName("Partners")
        Partners.resize(682, 514)
        Partners.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.centralwidget = QtWidgets.QWidget(parent=Partners)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("color: rgb(85, 255, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 656, 362))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.main_layout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.main_layout)
        self.AutoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 197, 100))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.AutoButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AutoButton.setFont(font)
        self.AutoButton.setStyleSheet("background-color: rgb(121, 197, 100);")
        self.AutoButton.setObjectName("AutoButton")
        self.verticalLayout.addWidget(self.AutoButton)
        Partners.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Partners)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 26))
        self.menubar.setObjectName("menubar")
        Partners.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Partners)
        self.statusbar.setObjectName("statusbar")
        Partners.setStatusBar(self.statusbar)


        self.retranslateUi(Partners)
        QtCore.QMetaObject.connectSlotsByName(Partners)

    def retranslateUi(self, Partners):
        _translate = QtCore.QCoreApplication.translate
        Partners.setWindowTitle(_translate("Partners", "MainWindow"))
        self.label.setText(_translate("Partners", "Партнёры"))
        self.AutoButton.setText(_translate("Partners", "Добавить партнера"))



class Partners(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Partners()
        self.ui.setupUi(self)
        self.ui.AutoButton.clicked.connect(self.on_clicked_add)
        self.load_partners()

    def load_partners(self):
        partners = db.show_partners()  # много строчек
        for partner in partners:
            discount = db.get_disc(int(partner["id"]))
            partner_info = PartnerCardInfo(
                partner["id"],
                partner["type_name"],
                partner["partner_name"],
                partner["first_name_director"],
                partner["last_name_director"],
                partner["middle_name_director"],
                partner["phone_partner"],
                partner["rating"],
                discount,
            )
            partnerCard = PartnerCard(partner_info)
            partnerCard.double_clicked.connect(self.load_choices)
            self.ui.verticalLayout_2.addWidget(partnerCard)

    #TODO: обработать двойной клик по карточке
    def load_choices(self, partner_info: PartnerCardInfo):
        from ui_py.AdminChoice import Admin

        self.Admin = Admin(partner_info)
        self.Admin.show()

    def on_clicked_add(self, partner_info):
        from ui_py.AddPartner import AddPartner

        self.AddPartner = AddPartner(partner_info)
        self.AddPartner.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Partners = QtWidgets.QMainWindow()
    ui = Ui_Partners()
    ui.setupUi(Partners)
    Partners.show()
    sys.exit(app.exec())
