# Form implementation generated from reading ui file 'partner_card.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from dataclasses import dataclass


class Ui_Frame(object):
    def setupUi(self, Frame):

        Frame.setObjectName("Frame")
        Frame.resize(400, 340)
        Frame.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comany = QtWidgets.QLabel(parent=Frame)
        self.comany.setStyleSheet(
            "color: rgb(121, 165, 100);\n" 'font: 75 12pt "MS Shell Dlg 2";'
        )
        self.comany.setObjectName("comany")
        self.horizontalLayout.addWidget(
            self.comany, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.percentage = QtWidgets.QLabel(parent=Frame)
        self.percentage.setStyleSheet(
            "color: rgb(121, 165, 70);\n" 'font: 75 12pt "MS Shell Dlg 2";'
        )
        self.percentage.setObjectName("percentage")
        self.horizontalLayout.addWidget(
            self.percentage, 0, QtCore.Qt.AlignmentFlag.AlignRight
        )
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ceo = QtWidgets.QLabel(parent=Frame)
        self.ceo.setStyleSheet(
            "color: rgb(121, 165, 100);\n" 'font: 75 12pt "MS Shell Dlg 2";\n' ""
        )
        self.ceo.setObjectName("ceo")
        self.verticalLayout.addWidget(self.ceo)
        self.name = QtWidgets.QLabel(parent=Frame)
        self.name.setStyleSheet(
            "color: rgb(121, 165, 100);\n" 'font: 75 12pt "MS Shell Dlg 2";'
        )
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.contacts = QtWidgets.QLabel(parent=Frame)
        self.contacts.setStyleSheet(
            "color: rgb(121, 165, 100);\n" 'font: 75 12pt "MS Shell Dlg 2";\n' ""
        )
        self.contacts.setObjectName("contacts")
        self.verticalLayout.addWidget(self.contacts)
        self.label = QtWidgets.QLabel(parent=Frame)
        self.label.setStyleSheet(
            "color: rgb(121, 165, 100);\n" 'font: 75 12pt "MS Shell Dlg 2";'
        )
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.comany.setText(_translate("Frame", "Тип | название компании"))
        self.percentage.setText(_translate("Frame", "Процент"))
        self.ceo.setText(_translate("Frame", "Директор"))
        self.name.setText(_translate("Frame", "ФИО"))
        self.contacts.setText(_translate("Frame", "Контакты"))
        self.label.setText(_translate("Frame", "Рейтинг:"))

